package script;

import static parent.GoogleSearch.driver;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import parent.GoogleSearch;

public class GoogleSearchPage extends GoogleSearch
{
    
	public  String searchString = "YouTube";
	public static List<WebElement> elements;
		
	
	//logic of google search and extracting result
	public void runTestScript()
	{
		driver.get("https://google.com");
		WebElement element = driver.findElement(By.name("q"));
		
				
		element.sendKeys(searchString);
		
		driver.findElement(By.className("gNO89b")).click();
		
		//searching for input string in results generated by google
		elements = driver.findElements(By.partialLinkText(searchString));		
		
	}
		

}
